apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: my-lan-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.200-192.168.1.254
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: my-lan-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - my-lan-pool
